# ===========
# CONFIG FILE
# ===========
#
# data
train_data: /home/jorisro/research/data/EM/EPFL/train
train_labels: /home/jorisro/research/data/EM/EPFL/train_labels
val_data: /home/jorisro/research/data/EM/EPFL/val
val_labels: /home/jorisro/research/data/EM/EPFL/val_labels
test_data: /home/jorisro/research/data/EM/EPFL/test
test_labels: /home/jorisro/research/data/EM/EPFL/test_labels
data_type: pngseq
# network
input_size: 256,256
fm: 16
levels: 4
dropout: 0.00
norm: batch
activation: relu
coi: 0,1
# optimization
loss: ce
lr: 0.001
epochs: 5
train_batch_size: 4
test_batch_size: 4
# compute
gpus: 0
num_workers: 12
accelerator: dp
# logging
log_dir: unet_2d
log_freq: 50
log_refresh_rate: -1
# reproducibility
seed: 0
