# ===========
# CONFIG FILE
# ===========
#
# data config
train_data: /home/jorisro/research/data/EM/EPFL/train
train_labels: /home/jorisro/research/data/EM/EPFL/train_labels
val_data: /home/jorisro/research/data/EM/EPFL/val
val_labels: /home/jorisro/research/data/EM/EPFL/val_labels
test_data: /home/jorisro/research/data/EM/EPFL/test
test_labels: /home/jorisro/research/data/EM/EPFL/test_labels
data_type: pngseq
# network config
input_size: 256,256
fm: 16
levels: 4
dropout: 0.00
norm: instance
activation: relu
in_channels: 1
classes_of_interest: 0,1
orientations: 0
# optimization config
loss: ce
lr: 0.001
step_size: 10
gamma: 0.9
epochs: 200
len_epoch: 1000
test_freq: 1
train_batch_size: 4
test_batch_size: 4
# compute config
gpus: 1
num_workers: 4
# logging config
log_dir: unet_2d
print_stats: 50
# remaining
seed: 0