# ===========
# CONFIG FILE
# ===========
#
# data
data: /home/jorisro/research/data/EM/EPFL/raw
labels: /home/jorisro/research/data/EM/EPFL/labels
train_val_test_split: 0.50,0.75
split_orientation: z
type: pngseq
# network
input_size: 16,64,64
fm: 16
levels: 4
dropout: 0.00
norm: batch
activation: relu
coi: 0,1
# optimization
loss: ce
lr: 0.001
epochs: 5
train_batch_size: 1
test_batch_size: 1
# compute
gpus: 0
num_workers: 12
accelerator: dp
# logging
log_dir: unet_3d
log_freq: 50
log_refresh_rate: -1
# reproducibility
seed: 0
