# ===========
# CONFIG FILE
# ===========
#
# data
data: /home/jorisro/research/data/EM/EPFL/raw
labels: /home/jorisro/research/data/EM/EPFL/labels
train_val_test_split: 0.50,0.75
split_orientation: z
type: pngseq
# network
input_size: 256,256
fm: 16
levels: 4
dropout: 0.00
norm: batch
activation: relu
coi: 0,1
# optimization
loss: ce
lr: 0.001
epochs: 1
train_batch_size: 4
test_batch_size: 4
# compute
gpus: 0
num_workers: 12
accelerator: dp
# logging
log_dir: unet_2d
log_freq: 50
log_refresh_rate: -1
# reproducibility
seed: 0
# grid search cross validation: search grid of the form param1:v1;v2;v3#param2:w1;w2#...
search_grid: feature_maps:8;16#input_shape:1,128,128;1,256,256
folds: 3
results_file: results.pickle